title: "Glossary"
repository_url: "https://github.com/carpentries/glosario"
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
kramdown:
  toc_levels: "2"
exclude:
  - "Makefile"
  - "README.md"
  - "bin/*"
  - "vendor"
languages:
  - key: af
    name: Afrikaans
    title: Woordelys
    blurb: >
      `glosario` is 'n oopbronwoordelys van terminologie wat in datawetenskap
      gebruik word en beskikbaar gestel word aanlyn sowel as 'n programmateek in
      [R](https://github.com/carpentries/glosario-r/) en [Python](https://github.com/carpentries/glosario-py/).
      Deur woordelyssleutels by 'n
      les se metadata in te sluit, kan outeurs aandui watter inligting in 'n les gedek
      word, wat leerders behoort te weet voordat die les begin en waar leerders
      die inligting kan vind. Outeurs kan ook die programmateekfunksies gebruik om
      konsekwente hiperskakels, vir terme en definisies in enige van verskeie tale,
      by hul lesse in te sluit.
  - key: am
    name: አማርኛ
    title: የቃላት ዝርዝር
    blurb: >
      In translation
  - key: ar
    name: Arabic
    title: قائمة المصطلحات
    blurb: >
      تطبيق (جلوساريو) هو عبارة عن برنامج مفتوح المصدر للمصطلحات المستخدمة في علم البيانات ، المتواجدة في
      [لغة آر (R)](https://github.com/carpentries/glosario-r/)
      و
      [لغة البايثون (Python)](https://github.com/carpentries/glosario-py/)
      عن طريق إضافة مفاتيح المصطلحات إلى البيانات الوصفية للدرس، يستطيع الكاتب ان يحدد
      ماهي مفاهيم الدرس، وماذا يجب على الطالب أن يتعلم قبل قراءة الدرس وأين يتمكن من تحصيل المعلومات
      كما يمكن للكاتب ان يحدد بعض المصطلحات ويربطها برابط يحتوي على ترجمة المصطلحات في عدة
      لغات
  - key: de
    name: Deutsch
    title: Glossar
    blurb: >
      `glosario` ist ein Open-Source-Glossar mit Begriffen aus
      Data-Science-Gebiet, das sowohl online als auch als Bibliothek
      in [R](https://github.com/carpentries/glosario-r/ und
      [Python](https://github.com/carpentries/glosario-py/) verfügbar
      ist. Durch Hinzufügen von Glossareinträgen zu den Metadaten
      einer Lektion (Lesson) können die Autoren angeben, was in in der
      Lektion gelehrt wird, was die Lernenden wissen sollten, bevor
      sie beginnen, und wo sie dieses Wissen finden können. Autoren
      können die Funktionen der Bibliothek auch nutzen, um konsistente
      Links zu Begriffe und Definitionen in ihren Lektionen in einer
      von mehreren Sprachen einzufügen.
  - key: en
    name: English
    title: Glossary
    blurb: >
      `glosario` is an open source glossary of terms used in data science that is
      available online and also as a library in both
      [R](https://github.com/carpentries/glosario-r/) and
      [Python](https://github.com/carpentries/glosario-py/).  By adding glossary
      keys to a lesson's metadata, authors can indicate what the lesson teaches,
      what learners ought to know before they start, and where they can go to find
      that knowledge.  Authors can also use the library's functions to insert
      consistent hyperlinks for terms and definitions in their lessons in any of
      several languages.
  - key: es
    name: Español
    title: Glosario
    blurb: >
      `glosario` es un glosario de fuente abierta de términos utilizados en la
      ciencia de datos que esta disponible en línea y también como libreria en
      [R](https://github.com/carpentries/glosario-r/) y
      [Python](https://github.com/carpentries/glosario-py/). Añadiendo entradas de
      glosario a los metadatos de una lección, las autoras pueden indicar lo que
      enseña la lección, lo que las alumnas deben saber antes de comenzar y adónde
      pueden ir para encontrar ese conocimiento. Las autoras también pueden
      utilizar las funciones de la libreria para insertar enlaces consistentes
      para términos y definiciones en sus lecciones en cualquiera de lenguajes
      severos.
  - key: fr
    name: Français
    title: Glossaire
    blurb: >
      `glosario` est un glossaire _open-source_ (à code source ouvert) pour les termes
      utilisés en science des données (_data science_) qui est disponible en ligne mais
      aussi sous forme de paquets pour [R](https://github.com/carpentries/glosario-r) et
      [Python](https://github.com/carpentries/glosario-py). En ajoutant des termes du
      glossaire dans les métadonnées de leçons, les auteurs peuvent indiquer ce
      qu'enseigne la leçon, ce que les élèves doivent savoir avant de commencer, et où
      les élèves peuvent aller pour trouver ces informations. Les auteurs de leçons
      peuvent aussi insérer des liens vers les définitions des termes utilisés dans leurs
      leçons, et ce, en plusieurs langages.
  - key: pt
    name: Português
    title: Glossário
    blurb: >
      `glosario` é um glossário de código aberto (_open source_) de termos utilizados
      em  ciência de dados (_data science_) que está disponível online, e também como
      um pacote de [R](https://github.com/carpentries/glosario-r/) e uma biblioteca
      de [Python](https://github.com/carpentries/glosario-py/). Ao adicionar termos
      do glossário nos metadados de uma lição, as pessoas autoras podem indicar o
      conteúdo da lição, o que as pessoas alunas precisam saber antes de começar,
      e onde podem procurar para encontrar estes conteúdos. As pessoas autoras também
      podem utilizar as funções das bibliotecas para inserir _links_ consistentes
      para termos e definições em suas lições, em qualquer idioma disponível.
  - key: ja
    name: 日本語
    title: グロサリオ
    flag: japan
    blurb: >
      `グロサリオ`は、データサイエンスで使われる用語の
      オープンソースグロッサリーです。オンラインとして、または
      [R](https://github.com/carpentries/glosario-r)パッケージや
      [Python](https://github.com/carpentries/glosario-py/)ライブラリ
      として利用出来ます。レッスンのメタデータに新しい用語を追加することで、
      そのレッスンで何を教えるのか、および学習者が必要な予備知識、
      そしてその情報がどこにあるかが分かるようになります。また、
      ライブラリの機能を使ってレッスンに多言語で、用語や定義に
      一貫したハイパーリンクを挿入することが可能になります。
  - key: nl
    name: Nederlands
    title: Woordenlijst
    blurb: >
      `glosario` is een openbron verklarende woordenlijst van terminologie die wordt gebruikt
      in de informatica en online beschikbaar wordt gesteld, evenals een programmabibliotheek in
      [R](https://github.com/carpentries/glosario-r/) en [Python](https://github.com/carpentries/glosario-py/).
      Door woordenlijstsleutels op te nemen in de metadata van een les, kunnen auteurs aangeven welke informatie
      in een les wordt behandeld, wat studenten moeten weten voordat de les begint en waar studenten de informatie
      kunnen vinden. Auteurs kunnen de tekenfuncties van het programma ook gebruiken om consistente doorklik op
      te nemen, voor termen en definities in een van de verschillende talen, in hun lessen.
  - key: zu
    name: IsiZulu
    title: Uhlu Lwamagama
    blurb: >
      `I-glosario` ingumhlahlandlela ovulekile womthombo wamagama asetshenziswe kusayensi yedatha etholakala
      ku-inthanethi njengomtapo wolwazi [ku-R](https://github.com/carpentries/glosario-r/)
      [naku-Python](https://github.com/carpentries/glosario-py/). Ngokufaka okhiye bohlu lwamagama kwimethadatha
      yesifundo, ababhali bangakhombisa ukuthi isifundo sifundisani, ukuthi yini abafundi okufanele bayazi
      ngaphambi kokuthi baqale, nokuthi bangaya kuphi ukuthola lolu lwazi. Ababhali bangasebenzisa futhi
      imisebenzi yomtapo ukufaka izixhumanisi ezihambisanayo zamagama nezincazelo ezifundweni zabo nganoma
      yiziphi izilimi eziningana.
