title: "Glossary"
repository: <USERNAME>/<PROJECT>
defaults:
- scope:
    path: ""
  values:
    layout: "page"
kramdown:
  toc_levels: "2"
exclude:
- "Makefile"
- "README.md"
- "bin/*"
languages:
- key: en
  name: English
  flag: united-kingdom
- key: es
  name: Español
  flag: spain
- key: fr
  name: Français
  flag: france
